services:

  gameplay:
    build: ./gameplay
    container_name: ${GAMEPLAY_NAME}
    command: daphne -b 0.0.0.0 -p ${GAMEPLAY_PORT} PongBackend.asgi:application
    environment:
      GAMEPLAY_SECRET_KEY: ${GAMEPLAY_SECRET_KEY}
      MICROSERVICE_SECRET_TOKEN: ${MICROSERVICE_SECRET_TOKEN}
    networks:
      - app-network
      - gameplay-redis-network
    expose:
      - ${GAMEPLAY_PORT}

  gameplay_redis:
    image: redis:latest
    container_name: gameplay_redis
    expose:
      - "6379"
    networks:
      - gameplay-redis-network

  lobby_api:
    build: ./lobby-api
    container_name: ${LOBBY_API_NAME}
    depends_on:
      - ${LOBBY_DB_NAME}
    environment:
      LOBBY_API_SECRET_KEY: ${LOBBY_API_SECRET_KEY}
      POSTGRES_DB: ${LOBBY_DB_NAME}
      POSTGRES_USER: ${LOBBY_DB_USER}
      POSTGRES_PASSWORD: ${LOBBY_DB_PASSWORD}
      PGPORT: ${LOBBY_DB_PORT}
    networks:
      - app-network
      - lobby-network
    expose:
      - ${LOBBY_API_PORT}

  lobby_db:
    image: postgres:15
    container_name: ${LOBBY_DB_NAME}
    restart: always
    environment:
      POSTGRES_DB: ${LOBBY_DB_NAME}
      POSTGRES_USER: ${LOBBY_DB_USER}
      POSTGRES_PASSWORD: ${LOBBY_DB_PASSWORD}
      PGPORT: ${LOBBY_DB_PORT}
    volumes:
      - lobby_db:/var/lib/postgresql/data
    networks:
      - lobby-network
    expose:
      - ${LOBBY_DB_PORT}

  lobby_websocket:
    build: ./lobby-websocket
    container_name: ${LOBBY_WEBSOCKET_NAME}
    command: daphne app.asgi:application -b 0.0.0.0 -p 8003
    environment:
      LOBBY_WEBSOCKET_SECRET_KEY: ${LOBBY_WEBSOCKET_SECRET_KEY}
    depends_on:
      - ${LOBBY_API_NAME}
      - lobby_redis
    networks:
      - app-network
      - lobby-redis-network
    expose:
      - ${LOBBY_WEBSOCKET_PORT}

  lobby_redis:
    image: redis:latest
    container_name: lobby_redis
    expose:
      - "6379"
    networks:
      - lobby-redis-network

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - ${LOBBY_API_NAME}
      - gameplay
    networks:
      - app-network
    volumes:
      - ./nginx/static:/usr/share/nginx/html

  userdata:
    container_name: userdata
    build:
      context: ./userdata/
      dockerfile: Dockerfile
    expose:
      - ${USERDATA_PORT}
    env_file:
      - ./.env
    depends_on:
      - userdata_db
    networks:
      - app-network
      - userdata-network
    volumes:
      - /home/${USER}/data/avatars:/home/app/web/avatars:rw

  userdata_db:
    container_name: userdata_db
    image: postgres:15
    volumes:
      - userdata_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${USERDATA_DB_USER}
      - POSTGRES_PASSWORD=${USERDATA_DB_PASSWORD}
      - POSTGRES_DB=${USERDATA_DB_NAME}
    networks:
      - userdata-network

networks:
  app-network:
    driver: bridge
  gameplay-redis-network:
    driver: bridge
  lobby-network:
    driver: bridge
  lobby-redis-network:
    driver: bridge
  userdata-network:
    driver: bridge

volumes:
  lobby_db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/lobby_db
  userdata_db:
    driver: local
    name: db_user
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/userdata_db